#' Generate ROSS Sensor Data
#'
#' This function reads, cleans, and compiles ROSS (Radical Open Science Syndicate)
#' sensor data from a specified directory. It automatically
#' identifies the correct data source folder for each year (e.g., post-verification, in-progress,
#' or HydroVu-flagged) based on folder structure and applies the appropriate
#' data processing pipeline. This function will generate the outputs for `load_sensor_data()`.
#'
#' Depending on the folder type, the function:
#' \itemize{
#'   \item Reads and merges raw or manually verified sensor files.
#'   \item Applies data cleaning and flag filtering (for HydroVu and pre-verified datasets).
#'   \item Applies interpolation to fill missing data, smoothing via a low-pass filter,
#'         and aggregates data to hourly medians.
#'   \item Adds a tag to specify what status the dataset has (e.g., auto_flagged, in_progress_verified, post_verification).
#'   \item Optionally saves the compiled dataset as a Parquet file for future use.
#' }
#'
#' @param data_dir Character. Path to the root directory containing
#'   sensor data organized by year-cycle (default:
#'   `here("data","raw","sensor","manual_data_verification")`).
#' @param output_directory Character. Path to the output directory for saving
#'   processed data if `update_data = TRUE` (default:
#'   `here("data","collated","sensor")`).
#' @param update_data Logical. If `TRUE`, the cleaned and compiled dataset
#'   will be saved as a Parquet file in the output directory (default: `FALSE`).
#'
#' @details
#' The function prioritizes data sources in the following order:
#' \enumerate{
#'   \item \strong{Post-verification data}: Used as-is, assuming it is finalized/prepared for use.
#'   \item \strong{In-progress data}: Combines verified and pre-verified datasets.
#'     - Verified datasets are filtered by manual verification flags.
#'     - Pre-verified datasets are processed with automated cleaning filters.
#'   \item \strong{HydroVu flagged data}: Raw HydroVu pulls that have undergone
#'     automated flagging are processed with standard QA/QC filters.
#'   \item \strong{HydroVu raw data}: Raises an error instructing the user to run
#'     the automated QA/QC routine first.
#' }
#'
#' Cleaning steps applied where applicable:
#' \itemize{
#'   \item Removal of sensor malfunction records (`mal_flag` != NA).
#'   \item Application of cleaning filters via `apply_cleaning_filters()`.
#'   This is only applied to non manually verified datasets.
#'   \item Interpolation of small data gaps via `apply_interpolation_missing_data()`.
#'   \item Smoothing using a binomial low-pass filter (`apply_low_pass_binomial_filter()`).
#'  This is only applied to optical sensors (e.g., turbidity, fDOM, chl-a).
#'   \item Aggregation to hourly medians (`apply_timestep_median()`).
#' }
#'
#' @return
#' A cleaned and compiled tibble (or data.table) of ROSS sensor data containing:
#' \itemize{
#'   \item `DT_round`: POSIXct timestamp (MST).
#'   \item `DT_join`: Character representation of timestamp for joins.
#'   \item `site`: Site identifier.
#'   \item `parameter`: Measured parameter name.
#'   \item `mean_cleaned`, `mean_filled`, `mean_smoothed`, `hourly_median`:
#'         Sequentially processed measurement columns.
#'   \item `flag`: QA/QC flag information. This is either autogenerated from the
#'   automated QA/QC process or user-defined during manual verification.
#'   \item `last_site_visit`: Datetime of the most recent field visit.
#'   \item `status`: Indicates the data source/status
#' }
#'
#' If `update_data = TRUE`, the same cleaned dataset is saved as a `.parquet` file
#' to the output directory named in the format:
#' `"compiled_ross_sensor_data_<date>.parquet"`.
#'
#' @examples
#' \dontrun{
#' # Load the most recent ROSS sensor data and update saved dataset
#' all_data <- generate_ross_sensor_data(update_data = TRUE)
#'
#' # Filter to 2023
#' data_2023 <- all_data %>%
#'  filter(lubridate::year(DT_round) == 2023)
#'
#' # Only use data that has been manually verified
#' verified_data <- all_data %>%
#' filter(status == "in_progress_verified" | status == "post_verification")
#'
#' #Filter to a specific site and parameter
#' site_param_data <- all_data %>%
#' filter(site == "sfm", parameter == "Turbidity")
#' }
#'
#' @seealso
#' apply_cleaning_filters(),apply_interpolation_missing_data(), apply_low_pass_binomial_filter(),
#' apply_timestep_median() and read_ext()
#'

generate_ross_sensor_data <- function(data_dir = here("data","raw", "sensor","manual_data_verification"),
                                      output_directory = here("data", "collated", "sensor"),
                                      update_data = FALSE){

  #---- Sourcing functions ----
  source("src/collation/read_ext.R")
  source("src/sensor_qaqc/apply_cleaning_filters.R")
  source("src/sensor_qaqc/apply_interpolation_missing_data.R")
  source("src/sensor_qaqc/apply_low_pass_binomial_filter.R")
  source("src/sensor_qaqc/apply_timestep_median.R")

  # Argument checks ----
  #check that data_dir exists
  if (!dir.exists(data_dir)) {
    stop(data_dir, "(data_dir) does not exist.")
  }
  if (!dir.exists(output_directory) && update_data) {
    dir.create(output_directory, recursive = TRUE)
    message("Created ross_output_directory: ", output_directory)
  }

  # Get folders in data_dir
  folders <- list.files(path = data_dir, full.names = T, pattern = "_cycle")
  years <- gsub("_cycle", "", basename(folders))

  cleaned_data <- map(years, function(year){
    #get the correct folder for the year
    path <- map2(year, data_dir, function(year, data_dir){
      #check to see if cycle exists
      folders <- list.files(path = file.path(data_dir, paste0(year, "_cycle")), full.names = T)
      if(length(folders) == 0){
        #message(paste("No data found for year", year))
        path = NULL
        return(path)
      }
      #check for post verification first
      if(any(grepl("post_verification", folders)) == TRUE){
        files <- list.files(path = file.path(data_dir, paste0(year, "_cycle"), "post_verification"), full.names = T)
        if(length(files) == 0){
          #message(paste("No post verification data found for year", year, ", moving to in_progress"))
        }else{
          #message(paste("Reading in post_verification data for year", year))
          path <- list(path =  file.path(data_dir, paste0(year, "_cycle"), "post_verification"),
                       status = "post_verification")
          return(path)
        }
      }

      #Check for in progress next
      if(any(grepl("in_progress", folders)) == TRUE ){
        files <- list.files(path = file.path(data_dir, paste0(year, "_cycle"), "in_progress"), full.names = T)
        if(length(files) == 0){
          #message(paste("No in progress verification data found for year", year, ", moving to autoqaqc/raw data"))

        }else{
          path <- list(path =  file.path(data_dir, paste0(year, "_cycle"), "in_progress"),
                       status = "in_progress")
          return(path)
        }
      }
      #check for HV folder
      if(any(grepl("hydro_vu_pull", folders)) == TRUE){
        #message(paste("No in progress verification data found for year", year, ", moving to autoqaqc/raw data"))
        folders <- list.files(path = file.path(data_dir, paste0(year, "_cycle"), "hydro_vu_pull"), full.names = T)
        if(length(folders) == 0){
          #message(paste("No raw data found for year", year))
          path = NULL
          return(path)
        }else{
          #see if any have flagged data in the folder name
          if(any(grepl("flagged_data", folders)) == TRUE ){
            path <- list(path =  file.path(data_dir, paste0(year, "_cycle"), "hydro_vu_pull", "flagged_data"),
                         status = "hv_flagged")
            return(path)
          }else{
            #if flagged data is not present, check for raw data
            if(any(grepl("raw_data", folders)) == TRUE){
              path <- list(path =  file.path(data_dir, paste0(year, "_cycle"), "hydro_vu_pull", "raw_data"),
                           status = "hv_raw")
              return(path)
            }else{
              #message(paste("No raw or flagged data found for year", year))
              path = NULL
              return(path)
            }

          }

        }

      }
    })[[1]]

    if(is.null(path)){
      message(paste("No data found for year", year))
      return(NULL)
    }
    message("Loading data from ", path$status, " for year ", year)

    #---- Data Processing based on folder ----
    #---- Hv Raw folder ----
    # Return data to user with message to run auto qaqc first for flagging and standardization
    if(path$status %in% c("hv_raw")){
      message("Data in hv_raw folder, please run autoqa_qc and save to the `hydro_vu_pull/flagged_data` folder")
      return(NULL)
    }
    #---- Hv Flagged folder----
    #read in all data from that folder
    if(path$status %in% c("hv_flagged")){
      message("Reading in flagged data from hv_flagged folder")
      #Get files
      files <- list.files(path = path$path, full.names = T)
      #read in files, parse and clean
      dataset <- map(files, ~ read_ext(.x))%>%
        bind_rows() %>%
        data.table() %>%
        #remove any obvious row errors/unusable data
        filter( !is.na(site), !is.na(parameter), !is.na(DT_round)) %>%
        #converting to MST for later use
        mutate(
          DT_round = with_tz(DT_round, tz = "MST"), #convert to MST for standardization
          DT_join = as.character(DT_round),
          last_site_visit = with_tz(last_site_visit, "MST"),
          mean = if_else(is.na(mal_flag), mean, NA) # remove reported sensor malfunctions
        )%>%
        filter(DT_round >= as.POSIXct(paste0(year, "-01-01 00:00:00"), tz = "MST") &
                 DT_round <= as.POSIXct(paste0(year, "-12-31 23:59:59"), tz = "MST")) %>%
        select(DT_round, DT_join, site, parameter, mean , auto_flag,mal_flag,  last_site_visit)

      message("Applying data cleaning")
      cleaned_data <- dataset %>%
        #these are to reduce overflagging of specific sites/parameters known to have issues
        apply_cleaning_filters(df = ., new_value_col = "mean_cleaned") %>%
        apply_interpolation_missing_data(df = ., value_col = "mean_cleaned", new_value_col = "mean_filled", max_gap = 4, method = "spline")%>%
        apply_low_pass_binomial_filter(df = ., value_col = "mean_filled", new_value_col = "mean_smoothed")%>%
        apply_timestep_median(df = ., timestep  = "1 hour", value_col = "mean_smoothed", new_value_col = "hourly_median")%>%
        mutate(status = "auto_flagged")
    }
    #---- In Progress folder ----
    # Preferentially using verified data where available, otherwise using pre-verified data with cleaning filters applied
    if(path$status %in% c("in_progress")){
      message("Reading in verified data from verified_directory")
      verified_names <- list.files(here(path$path, "verified_directory"), full.names = T)

      verified_dataset <- verified_names %>%
        map(\(file_path){
          site_parameter_df <- read_ext(file_path)
          return(site_parameter_df)
        }) %>%
        set_names(map_chr(., ~ paste0(unique(.x$site), "-", unique(.x$parameter))))%>%
        keep(., ~nrow(.x) > 0) #remove any empty datasets
      #Get names of verified datasets
      pre_verified_names_all <- list.files(here(path$path, "all_data_directory"), full.names = TRUE)
      # Filter out any names that are already in the verified dataset
      pre_verified_names <- pre_verified_names_all %>%
        keep(\(f) {
          fname <- basename(f)
          !any(str_detect(fname, fixed(names(verified_dataset))))
        })

      message("Reading in pre-verified data from all_data_directory")
      pre_verified_dataset <- pre_verified_names %>%
        map(\(file_path){
          site_parameter_df <- read_ext(file_path)
          return(site_parameter_df)
        }) %>%
        set_names(map_chr(., ~ paste0(unique(.x$site), "-", unique(.x$parameter))))%>%
        keep(., ~nrow(.x) > 0) #remove any empty datasets

      # Changes due to manual verification differences by year
      #2023 had a different manual verification protocol (which will not need to be repeated this way)
      if(year %in% c(2023, "2023")){
        message("Applying data cleaning")
        #Applying cleaning to verified data
        verified_df <-  verified_dataset%>%
          bind_rows()%>%
          mutate(
            #only accept data that is:
            #marked as PASS if a flag is absent
            #marked as FAIL if a flag is present
            mean_cleaned = case_when(
              is.na(flag) & verification_status == "PASS" ~ mean,
              is.na(flag) & verification_status == "FAIL" ~ NA,
              !is.na(flag) & verification_status == "PASS" ~ NA,
              !is.na(flag) & verification_status == "FAIL" ~ mean
            ),
            clean_flag = case_when(
              is.na(flag) & verification_status == "PASS" ~ NA,
              is.na(flag) & verification_status == "FAIL" ~ "MANUAL FLAG",
              !is.na(flag) & verification_status == "PASS" ~ flag,
              !is.na(flag) & verification_status == "FAIL" ~ NA
            ))%>%
          select(DT_round, DT_join, site, parameter, mean_cleaned, flag = clean_flag, last_site_visit)%>%
          mutate(status = "in_progress_verified")

        #Applying cleaning filters to pre-verified data (it is essentially autoqa_qc data)
        pre_verified_df <- pre_verified_dataset%>%
          bind_rows()%>%
          add_column_if_not_exists(., "mal_flag", NA_character_) %>%
          rename(auto_flag = flag) %>%
          #applying cleaning filters to pre-verified data
          apply_cleaning_filters(df = ., new_value_col = "mean_cleaned") %>%
          select(DT_round, DT_join, site, parameter, mean_cleaned, flag = clean_flag, last_site_visit)%>%
          mutate(status = "auto_flagged")

        #Bind datasets and process
        cleaned_data <- bind_rows(verified_df, pre_verified_df)%>%
          filter( !is.na(site), !is.na(parameter), !is.na(DT_round),
                  # Filter based on DT
                  DT_round >= as.POSIXct(paste0(year, "-01-01 00:00:00"), tz = "MST") &
                    DT_round <= as.POSIXct(paste0(year, "-12-31 23:59:59"), tz = "MST"))%>%
          mutate(last_site_visit = with_tz(last_site_visit, tzone = "MST")) %>%
          #apply interpolation, smoothing and hourly median
          apply_interpolation_missing_data(df = ., value_col = "mean_cleaned", new_value_col = "mean_filled", max_gap = 4, method = "spline")%>%
          apply_low_pass_binomial_filter(df = ., value_col = "mean_filled", new_value_col = "mean_smoothed")%>%
          apply_timestep_median(df = ., timestep  = "1 hour", value_col = "mean_smoothed", new_value_col = "hourly_median")
      }
      #---- Any year other than 2023 ----
      if(!year %in% c(2023, "2023")){
        message("Applying data cleaning")
        #Applying cleaning to verified data
        verified_df <-  verified_dataset%>%
          bind_rows()%>%
          mutate(
            #only accept data that is marked as PASS or FLAGGED, omit OMIT data
            mean_cleaned = case_when(
              verification_status == "OMIT"  ~ NA,
              verification_status == "PASS" ~ mean,
              verification_status == "FLAGGED" ~ mean
            ),
            # pass user designated flags through
            clean_flag = case_when(
              verification_status == "OMIT"  ~ NA,
              verification_status == "PASS" ~  NA,
              verification_status == "FLAGGED" ~ user_flag
            ))%>%
          select(DT_round, DT_join, site, parameter, mean, mean_cleaned, clean_flag, last_site_visit)%>%
          mutate(status = "in_progress_verified")

        #Applying cleaning filters to pre-verified data (it is essentially autoqa_qc data)
        pre_verified_df <- pre_verified_dataset%>%
          bind_rows()%>%
          #applying cleaning filters to pre-verified data
          apply_cleaning_filters(df = ., new_value_col = "mean_cleaned") %>%
          select(DT_round, DT_join, site, parameter, mean_cleaned, clean_flag, last_site_visit)%>%
          mutate(status = "auto_flagged")

        #Bind datasets and process
        cleaned_data <- bind_rows(verified_df, pre_verified_df) %>%
          filter( !is.na(site), !is.na(parameter), !is.na(DT_round),
                  # Filter based on DT
                  DT_round >= as.POSIXct(paste0(year, "-01-01 00:00:00"), tz = "MST") &
                    DT_round <= as.POSIXct(paste0(year, "-12-31 23:59:59"), tz = "MST"))%>%
          mutate(last_site_visit = with_tz(last_site_visit, tzone = "MST")) %>%
          #apply interpolation, smoothing and hourly median
          apply_interpolation_missing_data(df = ., value_col = "mean_cleaned", new_value_col = "mean_filled", max_gap = 4, method = "linear")%>%
          apply_low_pass_binomial_filter(df = ., value_col = "mean_filled", new_value_col = "mean_smoothed")%>%
          apply_timestep_median(df = ., timestep  = "1 hour", value_col = "mean_smoothed", new_value_col = "hourly_median")
      }
    }

    #---- Post Verification folder----
    if(path$status %in% c("post_verification")){
      message("Data in post_verification, no cleaning applied")
      #get files
      files <- list.files(path = path$path, full.names = T)
      cleaned_data <- map(files, ~ read_ext(.x))%>%
        bind_rows() %>%
        data.table() %>%
        #remove any obvious row errors/unusable data
        filter( !is.na(site), !is.na(parameter), !is.na(DT_round))%>%
        #converting to MST for later use
        mutate(
          DT_round = with_tz(DT_round, tz = "MST"),
          DT_join = as.character(DT_round),
          last_site_visit = with_tz(last_site_visit, "MST"),
          mean = if_else(is.na(mal_flag), mean, NA) # remove reported sensor malfunctions
        )%>%
        filter(DT_round >= as.POSIXct(paste0(year, "-01-01 00:00:00"), tz = "MST") &
                 DT_round <= as.POSIXct(paste0(year, "-12-31 23:59:59"), tz = "MST"))%>%
        mutate(status = "post_verification")
    }
    return(cleaned_data)
  })

  complete_dataset <- cleaned_data%>%
    keep(~!all(is.na(.x)))%>% #remove years without data
    bind_rows()%>%
    select(DT_round, site, parameter, mean, clean_flag, mean_cleaned, mean_filled, mean_smoothed, hourly_median, last_site_visit, status)%>%
    #fix any issues with site names
    fix_site_names()%>%
    mutate(site = gsub(pattern = " virridy",replacement =  "_virridy",x =  site),
           site = gsub("spring creek", "spring_creek", site))
  #---- Saving updated cleaned data ----
  if(update_data){
    date <- Sys.Date()
    file_name <- paste0("compiled_ross_sensor_data_" , date, ".parquet")
    output_path <- file.path(output_directory, file_name)
    write_parquet(complete_dataset, output_path)
    message("Saved updated ROSS sensor data to: ", output_path)
  }

  return(complete_dataset)
}

