---
title: "Intake daily TOC baseline"
author: "ROSSyndicate"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)

library(tidyverse)
library(cdssr)
library(snotelr)
library(mgcv)
library(Metrics)
```

# Purpose

This document explores some options for modeling daily TOC data from the City of 
Fort Collins' intake.

# Data

```{r}
# intake TOC
fc_intake <- read_csv(here("data/collated/FC_intake/fc_intake_TOC_record_2010-2025.csv"))

# read in flow data at canyon mouth
flow_data <- get_sw_ts(abbrev = "CLAFTCCO",
                       start_date = "2010-01-01",
                       end_date = "2025-12-31",
                       timescale = "day") %>%
  select(datetime, canyon_mouth_cfs = value) %>% 
  mutate(date = date(datetime), 
         year = year(date),
         doy = yday(date)) 

# grab sites in the HUC
snotel_sites <- snotel_info() %>%
  filter(grepl("10190007", description))

# Download daily SNOTEL data
snotel_data <- snotel_download(site_id = snotel_sites$site_id,
                               internal = TRUE,
                               metric = TRUE) %>% 
  mutate(date = ymd(date),
         doy = yday(date),
         year = year(date))

# prep for PCA
snotel_matrix <- snotel_data %>%
  select(date, site_id, snow_water_equivalent) %>% 
  pivot_wider(names_from = site_id, 
              names_prefix = "swe_",
              values_from = snow_water_equivalent) %>% 
  .[complete.cases(.), ]

# run PCA
pca_snotel <- snotel_matrix %>% 
  select(starts_with("swe_")) %>% 
  prcomp(., center = TRUE, scale. = TRUE) 
 
# make the dataframe
snotel <- tibble(swe_pca = pca_snotel$x[,1], date = snotel_matrix$date) 

# calculate melt from PCA statistic
snotel <- snotel %>% 
  arrange(date) %>% 
  mutate(date_m14 = date - days(14), 
         date_m7 = date - days(7),
         date_m3 = date - days(3)) %>%
  # join for differences
  left_join(snotel %>%
              select(date, swe_pca) %>%
              rename(date_m14 = date,
                     swe_pca_lag14 = swe_pca),
            by = "date_m14") %>%
  left_join(snotel %>%
              select(date, swe_pca) %>%
              rename(date_m7 = date,
                     swe_pca_lag7 = swe_pca),
            by = "date_m7") %>%
  left_join(snotel %>% 
              select(date, swe_pca) %>% 
              rename(date_m3 = date,
                     swe_pca_lag3 = swe_pca)) %>% 
  # compute melt rate
  mutate(melt_rate_14d = (swe_pca_lag14 - swe_pca) / 14,
    melt_rate_7d = (swe_pca_lag7 - swe_pca) / 7,
    melt_rate_3d = (swe_pca_lag3 - swe_pca) / 3) %>% 
  select(-c(date_m14, swe_pca_lag14,
            date_m7, swe_pca_lag7, 
            date_m3, swe_pca_lag3))

intake_flow_swe <- left_join(fc_intake, flow_data) %>% 
  left_join(snotel)
```

# Visualize TOC

```{r}
ggplot(intake_flow_swe, aes(x = date, y = mean_TOC)) +
  geom_point() +
  theme_bw() +
  labs(x = "day of year",
       y = "intake TOC (mg/L)")

intake_flow_swe %>% 
  summarize(max_TOC = max(mean_TOC),
            mean_TOC = mean(mean_TOC),
            n_TOC = n(), 
            .by = year) %>% 
  arrange(year)
```

# Pull testing data

Given the 16 years of data, we're going to be cautious from the top and pull out
a test set of 2 years of data.

```{r}
test_years <- c(2018, 2024)

test <- intake_flow_swe %>% 
  filter(year %in% test_years)

training <- anti_join(intake_flow_swe, test)
```

# Play with training data

```{r}
gam_doy <- gam(mean_TOC ~ s(doy, bs = "cc"),
               data = training, 
               method = "REML")

gam.check(gam_doy)
```

```{r}
gam_doy_q <- gam(mean_TOC ~ s(doy, bs = "cc") + s(canyon_mouth_cfs),
                 data = training,
                 method = "REML")

gam.check(gam_doy_q)
```

```{r}
gam_doy_q_swe <- gam(
  mean_TOC ~ 
    s(doy, bs = "cc") +
    s(canyon_mouth_cfs) +
    ti(doy, canyon_mouth_cfs, bs = c("cc", "tp")) +
    s(swe_pca, bs = "ts"),
  data   = training,
  method = "REML"
)

gam.check(gam_doy_q_swe)
```

```{r}
gam_doy_q_swe_melt <- gam(
  mean_TOC ~ 
    s(doy, bs = "cc") +
    s(canyon_mouth_cfs, bs = "tp") +
    s(melt_rate_7d, bs = "tp") +
    ti(melt_rate_7d, canyon_mouth_cfs, bs = "tp"),
  data   = training,
  method = "REML"
)

gam.check(gam_doy_q_swe_melt)
```

```{r}
gam_doy_q_swe_melt_14 <- gam(
  mean_TOC ~ 
    s(doy, bs = "cc") +
    s(canyon_mouth_cfs, bs = "tp") +
    #s(melt_rate_7d, bs = "tp") +
    s(melt_rate_14d, bs = "tp") +
    ti(melt_rate_14d, canyon_mouth_cfs, bs = "tp"),
  data   = training,
  method = "REML"
)

gam.check(gam_doy_q_swe_melt_14)
```


# Apply to test set

```{r}
test$pred_TOC_best <- predict(gam_doy_q_swe_melt_14, test)
test$pred_TOC_simple <- predict(gam_doy_q, test)

ggplot(test, aes(x = mean_TOC, y = pred_TOC_best)) +
  geom_point() +
  theme_bw() +
  geom_abline(slope = 1, intercept = 0) +
  coord_cartesian(xlim = c(1,12.5), ylim = c(1, 12.5)) +
  labs(x = "measured TOC @ intake (mg/L)",
       y = "predicted TOC @ intake (mg/L)")

rmse(test$mean_TOC, test$pred_TOC_best)
mae(test$mean_TOC, test$pred_TOC_best)
bias(test$mean_TOC, test$pred_TOC_best)

ggplot(test, aes(x = mean_TOC, y = pred_TOC_simple)) +
  geom_point() +
  theme_bw() +
  geom_abline(slope = 1, intercept = 0) +
  coord_cartesian(xlim = c(1,12.5), ylim = c(1, 12.5)) +
  labs(x = "measured TOC @ intake (mg/L)",
       y = "predicted TOC @ intake (mg/L)")

rmse(test$mean_TOC, test$pred_TOC_simple)
mae(test$mean_TOC, test$pred_TOC_simple)
bias(test$mean_TOC, test$pred_TOC_simple)

```

